/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author paulo.ti
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktopainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnarquivosclientes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnarquivosprodutos = new javax.swing.JMenuItem();
        mnarquivosusuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnarquivosalterarsenha = new javax.swing.JMenuItem();
        mnarquivosalterarusuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnarquivossair = new javax.swing.JMenuItem();
        mnmovimentos = new javax.swing.JMenu();
        mnmovimentosvendas = new javax.swing.JMenuItem();
        mnmovimentosrelatorios = new javax.swing.JMenuItem();
        mnajudasobre = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        mnajudaajuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Java");

        Desktopainel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout DesktopainelLayout = new javax.swing.GroupLayout(Desktopainel);
        Desktopainel.setLayout(DesktopainelLayout);
        DesktopainelLayout.setHorizontalGroup(
            DesktopainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopainelLayout.setVerticalGroup(
            DesktopainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnarquivosclientes.setText("Arquivos");

        jMenuItem1.setText("Clientes");
        mnarquivosclientes.add(jMenuItem1);

        mnarquivosprodutos.setText("Produtos");
        mnarquivosclientes.add(mnarquivosprodutos);

        mnarquivosusuarios.setText("Usuários");
        mnarquivosusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnarquivosusuariosActionPerformed(evt);
            }
        });
        mnarquivosclientes.add(mnarquivosusuarios);
        mnarquivosclientes.add(jSeparator1);

        mnarquivosalterarsenha.setText("Alterar Senha");
        mnarquivosclientes.add(mnarquivosalterarsenha);

        mnarquivosalterarusuario.setText("Alterar Usuário");
        mnarquivosclientes.add(mnarquivosalterarusuario);
        mnarquivosclientes.add(jSeparator2);

        mnarquivossair.setText("Sair");
        mnarquivosclientes.add(mnarquivossair);

        jMenuBar1.add(mnarquivosclientes);

        mnmovimentos.setText("Movimentos");

        mnmovimentosvendas.setText("Vendas");
        mnmovimentos.add(mnmovimentosvendas);

        mnmovimentosrelatorios.setText("Relatórios de Vendas");
        mnmovimentos.add(mnmovimentosrelatorios);

        jMenuBar1.add(mnmovimentos);

        mnajudasobre.setText("Ajuda");

        jMenuItem9.setText("Sobre");
        mnajudasobre.add(jMenuItem9);

        mnajudaajuda.setText("Ajuda");
        mnajudasobre.add(mnajudaajuda);

        jMenuBar1.add(mnajudasobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktopainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktopainel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnarquivosusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnarquivosusuariosActionPerformed
        //ESTE CÓDIGO É DO BOTÃO mnmenu usuários
        // istancia formulario
        frmusuarios fusuario = new frmusuarios();
        Desktopainel.add(fusuario);
        fusuario.show();
    }//GEN-LAST:event_mnarquivosusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktopainel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnajudaajuda;
    private javax.swing.JMenu mnajudasobre;
    private javax.swing.JMenuItem mnarquivosalterarsenha;
    private javax.swing.JMenuItem mnarquivosalterarusuario;
    private javax.swing.JMenu mnarquivosclientes;
    private javax.swing.JMenuItem mnarquivosprodutos;
    private javax.swing.JMenuItem mnarquivossair;
    private javax.swing.JMenuItem mnarquivosusuarios;
    private javax.swing.JMenu mnmovimentos;
    private javax.swing.JMenuItem mnmovimentosrelatorios;
    private javax.swing.JMenuItem mnmovimentosvendas;
    // End of variables declaration//GEN-END:variables
}
